export const THEMES = [
    "dark",
    "light",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthware",
    "retro",
    "valentine",
    "forest",
    "wireframe",
    "black",
    "luxury",
    "coffee",
    "winter",
]